server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    accept-count: 800

spring:
  aop:
    auto: true
  messages:
    basename: message
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.121.35:3306/qy_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: mayi.9860869
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 1000
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

